[package]
name = "image_processor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.22.0"
data-url = "0.3.1"
image = "0.24.9"
wasm-bindgen = "0.2.91"

[dev-dependencies]
wasm-bindgen-test = "0.3.41"
